module tomato {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.swing;
    requires com.google.gson;
    requires java.desktop;
    requires java.net.http;
    requires jdk.httpserver;
    requires com.jcraft.jsch;
    requires java.sql;
    requires mysql.connector.j;
    requires org.postgresql.jdbc;
    requires org.fxmisc.richtext;
    requires org.fxmisc.flowless;
    requires org.fxmisc.undo;
    requires reactfx;
    requires org.apache.commons.compress;
    requires org.apache.commons.codec;
    requires org.apache.commons.io;
    requires rdp;
    requires org.bouncycastle.provider;
    requires org.bouncycastle.tls;
    requires minio;
    requires aliyun.sdk.oss;
    requires aliyun.java.sdk.core;
    requires aliyun.java.sdk.ecs;
    requires aliyun.java.sdk.domain;
    requires aliyun.java.sdk.alidns;
    requires redis.clients.jedis;
    requires rocketmq.tools;
    requires rocketmq.remoting;
    requires rocketmq.common;
    requires rocketmq.client;
    requires rocketmq.acl;
    requires rocketmq.srvutil;
    requires kafka.clients;
    requires org.apache.commons.lang3;
    requires slf4j.api;
    requires org.apache.xmlgraphics.batik.transcoder;
    requires org.apache.xmlgraphics.batik.codec;
    requires org.apache.xmlgraphics.batik.dom;
    requires org.apache.xmlgraphics.batik.svgdom;
    requires org.apache.xmlgraphics.batik.brdige;
    requires org.apache.xmlgraphics.batik.gvt;
    requires org.apache.xmlgraphics.batik.util;
    requires org.apache.xmlgraphics.batik.css;
    requires org.apache.xmlgraphics.batik.parser;
    requires org.apache.xmlgraphics.batik.anim;
    requires org.apache.xmlgraphics.batik.awt.util;
    requires org.apache.xmlgraphics.batik.constants;
    requires org.apache.xmlgraphics.batik.ext;
    requires org.apache.xmlgraphics.batik.i18n;
    requires org.apache.xmlgraphics.batik.script;
    requires org.apache.xmlgraphics.batik.xml;
    requires org.commonmark;
    requires flexmark;
    requires flexmark.ext.abbreviation;
    requires flexmark.ext.aside;
    requires flexmark.ext.gfm.strikethrough;
    requires flexmark.ext.gfm.tasklist;
    requires flexmark.ext.tables;
    requires flexmark.ext.wikilink;
    requires flexmark.util.ast;
    requires flexmark.util.html;
    requires flexmark.util.misc;
    requires flexmark.util.sequence;
    requires de.jensd.fx.glyphs.commons;
    requires de.jensd.fx.glyphs.fontawesome;
    requires com.fasterxml.jackson.databind;
    requires com.google.common;
    requires java.prefs;
    requires com.miglayout.javafx;

    opens com.tangluobo.tomato to javafx.fxml;
    exports com.tangluobo.tomato;
    exports com.tangluobo.tomato.module;
    opens com.tangluobo.tomato.module to javafx.fxml;
    exports com.tangluobo.tomato.module.connect;
    opens com.tangluobo.tomato.module.connect to javafx.fxml, com.google.gson;
    exports com.tangluobo.tomato.module.settings;
    opens com.tangluobo.tomato.module.settings to javafx.fxml;
    exports com.tangluobo.tomato.module.tools;
    opens com.tangluobo.tomato.module.tools to javafx.fxml, com.google.gson;
    exports com.tangluobo.tomato.module.tools.extractor;
    opens com.tangluobo.tomato.module.tools.extractor to javafx.fxml;
    exports com.tangluobo.tomato.module.tools.server;
    opens com.tangluobo.tomato.module.tools.server to javafx.fxml, com.google.gson;
    exports com.tangluobo.tomato.module.server;
    opens com.tangluobo.tomato.module.server to javafx.fxml;
    exports com.tangluobo.tomato.utils;
    opens com.tangluobo.tomato.utils to com.google.gson, javafx.fxml;
    exports com.tangluobo.tomato.ssh;
    opens com.tangluobo.tomato.ssh to javafx.fxml;
    exports com.tangluobo.tomato.rdp;
    opens com.tangluobo.tomato.rdp to javafx.fxml;
    exports com.tangluobo.tomato.ssh.zmodem;
    exports com.tangluobo.tomato.ssh.zmodem.xfer.util;
    exports com.tangluobo.tomato.ssh.zmodem.xfer.zm.util;
    exports com.tangluobo.tomato.ssh.zmodem.xfer.zm.packet;
    exports com.tangluobo.tomato.ssh.zmodem.xfer.zm.proto;
    exports com.tangluobo.tomato.ssh.zmodem.xfer.io;
    exports com.tangluobo.tomato.ssh.zmodem.zm.io;
    exports com.tangluobo.tomato.ssh.zmodem.util;
    exports com.tangluobo.tomato.module.connect.dialog;
    opens com.tangluobo.tomato.module.connect.dialog to com.google.gson, javafx.fxml;
    exports com.tangluobo.tomato.module.connect.handler;
    opens com.tangluobo.tomato.module.connect.handler to com.google.gson, javafx.fxml;
    exports com.tangluobo.tomato.module.connect.service;
    opens com.tangluobo.tomato.module.connect.service to com.google.gson, javafx.fxml;
    exports com.tangluobo.tomato.module.connect.view;
    opens com.tangluobo.tomato.module.connect.view to com.google.gson, javafx.fxml;
}
